version: '3'
services:
  web:
    build: .
    ports:
    - "8070:8070"
    volumes:
    - .:/go/src/app
    depends_on:
    - mongo
    links:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
